import { useEffect, useState } from 'react';
import { InferGetServerSidePropsType } from 'next';
import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import People from '../components/People';

const Home: NextPage = () => {
	const [name, setName] = useState<string>('');
	const [age, setAge] = useState<number>(0);
	const [race, setRace] = useState<'white' | 'black' | 'yellow'>('white');

	const { data, isLoading, refetch } = trpc.useQuery([
		'example.hello',
		{
			person: {
				name,
				age,
				race,
			},
		},
	], {
		enabled: false,
	});

	const { isLoading: isCreatePostLoading, mutate: createPerson } = trpc.useMutation(['person.createPerson'], {
		onSuccess(data) {
			refetch();
			console.log('Person created successfully', data);
		},
		onError(error) {
			console.error(error);
		},
	});

	useEffect(() => {
		refetch();
	}, [refetch, name, age, race]);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<h1>
					Racial Profiling App
				</h1>

				<div>
					<label>
						Name:
						<input type="string" value={name} onChange={(e) => {
							setName(e.currentTarget.value);
						}} />
					</label>

					<br />

					<label>
						Age:
						<input type="number" min={0} value={age} onChange={(e) => {
							setAge(+e.currentTarget.value);
						}} />
					</label>

					<br />

					<label>
						Race:
						<select value={race} onChange={(e) => {
							setRace(e.currentTarget.value as 'white' | 'black' | 'yellow');
						}}>
							<option value="white">White</option>
							<option value="black">Black</option>
							<option value="yellow">Yellow</option>
						</select>
					</label>

					<br />

					<button onClick={() => {
						createPerson({
							name,
							age,
							race,
						});
					}}>Save character</button>

					<div>{data ? <p>{data.greeting}</p> : <p>Loading..</p>}</div>

					<People />
				</div>
			</div>
		</>
	);
};

export default Home;